# Server Configuration
server.port=8080

# SpringDoc OpenAPI Configuration
logging.level.org.springdoc=DEBUG
logging.level.org.springframework=DEBUG
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.packages-to-scan=br.com.productshop.marketplace_api
springdoc.paths-to-match=/api/**,/products/**

# Logging Configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.springdoc=DEBUG
